Page({
    data:{
        minaList:[
            {
                "id":1,
                "name":"京东购物",
                "img":"http://renhongjin.org/imgs/jd.jpg",
                "qr":"http://renhongjin.org/imgs/jd.jpg",
                "desc":"京东购物官方小程序，京东买买买更多样了。",
                "useTime":"100000+",
                "tags":[
                    {
                        "id":"1",
                        "name":"购物"
                    },
                    {
                        "id":"1",
                        "name":"科技"
                    }
                ]
            },
            {
                "id":2,
                "name":"滴滴出行DIDI",
                "img":"http://renhongjin.org/imgs/didi.jpg",
                "qr":"http://renhongjin.org/imgs/didi.jpg",
                "desc":"滴滴一下，随叫随到。滴滴出行小程序版，迅速，快捷。",
                "useTime":"100000+",
                "tags":[
                    {
                        "id":"1",
                        "name":"出行"
                    },
                    {
                        "id":"1",
                        "name":"科技"
                    },
                    {
                        "id":"1",
                        "name":"工具"
                    }
                ]
            },
            {
                "id":3,
                "name":"去哪儿出行",
                "img":"http://renhongjin.org/imgs/qunar.jpg",
                "qr":"http://renhongjin.org/imgs/qunar.jpg",
                "desc":"“去哪儿旅行”的双胞胎弟弟“去哪儿出行”，光速抢票，极速出票，免登录，可预约，2步预订飞机，火车，汽车，各种票。回家买票的路上不再孤单，去哪儿出行为您保驾护航。",
                "useTime":"1000",
                "tags":[
                    {
                        "id":"1",
                        "name":"机票"
                    },
                    {
                        "id":"1",
                        "name":"旅游"
                    },
                    {
                        "id":"1",
                        "name":"工具"
                    }
                ]
            },
            {
                "id":3,
                "name":"王者荣耀赛事",
                "img":"http://renhongjin.org/imgs/wzry.jpg",
                "qr":"http://renhongjin.org/imgs/wzry.jpg",
                "desc":"“直播类小程序，收集了王者荣耀的各类直播",
                "useTime":"1000",
                "tags":[
                    {
                        "id":"1",
                        "name":"游戏"
                    },{
                        "id":"1",
                        "name":"直播"
                    }
                ]
            },
            {
                "id":1,
                "name":"融360诚信助手",
                "img":"http://bugua.oss-cn-beijing.aliyuncs.com/mini-app/icon/0d8263f541760c959a9cf355d120630f.jpg",
                "qr":"http://bugua.oss-cn-beijing.aliyuncs.com/mini-app/qrcode/0d8263f541760c959a9cf355d120630f.jpg",
                "desc":"一键查询征信黑名单，关注信用健康，从我做起。信息来源：法院失信名单，分类信息中介黑名单，贷款机构黑名单等。",
                "useTime":2,
                "tags":[
                    {
                        "id":"1",
                        "name":"工具"
                    },
                    {
                        "id":"1",
                        "name":"科技"
                    }
                ]
            },
            {
                "id":2,
                "name":"南京环宇城会员福利",
                "img":"http://bugua.oss-cn-beijing.aliyuncs.com/mini-app/icon/ba62de49395abeb9b344ee647c94004b.jpg",
                "qr":"http://bugua.oss-cn-beijing.aliyuncs.com/mini-app/qrcode/ba62de49395abeb9b344ee647c94004b.jpg",
                "desc":"南京环宇城会员专享福利，电影票、停车券、餐饮券都在这儿了。",
                "useTime":10,
                "tags":[
                    {
                        "id":"1",
                        "name":"IT工具"
                    },
                    {
                        "id":"1",
                        "name":"科技"
                    }
                ]
            },
            {
                "id":3,
                "name":"开眼壁纸",
                "img":"http://bugua.oss-cn-beijing.aliyuncs.com/mini-app/icon/35a9c80a58c4270c8fd1d6de6851729d.jpg",
                "qr":"http://bugua.oss-cn-beijing.aliyuncs.com/mini-app/qrcode/35a9c80a58c4270c8fd1d6de6851729d.jpg",
                "desc":"设计师精挑细选的海量高清高品质壁纸，涵盖风景、运动、旅行等多种分类，让你大开眼界。",
                "useTime":20,
                "tags":[
                    {
                        "id":"1",
                        "name":"IT工具"
                    },
                    {
                        "id":"1",
                        "name":"科技"
                    }
                ]
            },
            {
                "id":4,
                "name":"选车神器",
                "img":"http://bugua.oss-cn-beijing.aliyuncs.com/mini-app/icon/2f28e8380442d6b06b93989a7323729d.jpg",
                "qr":"http://bugua.oss-cn-beijing.aliyuncs.com/mini-app/qrcode/2f28e8380442d6b06b93989a7323729d.jpg",
                "desc":"功能强大的筛选器，帮你找到想买的车！提供车辆性价对比。（特别提示：小程序只能用微信扫二维码，不能直接在微信里识别二维码哟）",
                "useTime":0,
                "tags":[
                    {
                        "id":"1",
                        "name":"IT工具"
                    },
                    {
                        "id":"1",
                        "name":"科技"
                    }
                ]
            }
        ]
    },
    use : function () {
        wx.showModal({
            title: "温馨提示",
            content: "复制小程序标题到小程序搜索栏搜索，开始你的小程序之旅吧",
            showCancel: false,
            confirmText: "确定"
    })
    },
    //自定义分享标题
  onShareAppMessage: function () {
    return {
      title: '我分享而更好',
      path: 'pages/list/list'
    }
  }, 
  searchText:function(e){
      console.log(xx)
    console.log(e.detail.value)
  }
})